const $=s=>document.querySelector(s);document.documentElement.classList.add('js');
const heroes=[['phantom_assassin','Phantom Assassin'],['juggernaut','Juggernaut'],['pudge','Pudge'],['invoker','Invoker'],['drow_ranger','Drow Ranger'],['nevermore','Shadow Fiend']];
let switchTimer;heroes.forEach(([id,name],index)=>{const b=document.createElement('button');b.innerHTML=`<img src="assets/hero_${id}.png" alt="">`;b.setAttribute('aria-label',name);b.setAttribute('aria-pressed',String(index===0));b.addEventListener('click',()=>{clearTimeout(switchTimer);$('.hero-stage img').classList.add('switching');switchTimer=setTimeout(()=>{$('#heroArt').src=`assets/render_${id}.png`;$('#heroArt').alt=name+' из Dota 2';$('#heroName').textContent=name;$('.hero-selection-caption .muted').textContent=`0${index+1} / 06`;document.querySelectorAll('.hero-selector button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('#heroArt').classList.remove('switching');},180)});$('.hero-selector').append(b)});
const reduce=matchMedia('(prefers-reduced-motion: reduce)');let motion=!reduce.matches;const motionButton=$('#motionToggle');function setMotion(value){motion=value;document.body.classList.toggle('no-motion',!value);motionButton.textContent=`Анимации: ${value?'вкл.':'выкл.'}`;motionButton.setAttribute('aria-pressed',String(value))}setMotion(motion);motionButton.onclick=()=>setMotion(!motion);reduce.addEventListener('change',e=>setMotion(!e.matches));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));new IntersectionObserver(entries=>entries.forEach(e=>document.body.classList.toggle('paused',!e.isIntersecting)),{threshold:0}).observe($('.hero'));document.addEventListener('visibilitychange',()=>document.body.classList.toggle('paused',document.hidden));
let queued=false;function progress(){const height=document.documentElement.scrollHeight-innerHeight;$('.scroll-progress').style.transform=`scaleX(${height>0?scrollY/height:0})`;queued=false}addEventListener('scroll',()=>{if(!queued){queued=true;requestAnimationFrame(progress)}},{passive:true});addEventListener('resize',progress);progress();
const data={heroes:['ОБРАЗЫ / СТИЛИ / ЭФФЕКТЫ','Тот самый герой.<br>Новый взгляд.','Подбирай предметы, переключай доступные стили и сохраняй любимые сочетания в пресеты.','<img src="assets/render_juggernaut.png" alt="Juggernaut"><img src="assets/render_invoker.png" alt="Invoker"><img src="assets/render_drow_ranger.png" alt="Drow Ranger">'],couriers:['КУРЬЕРЫ / САМОЦВЕТЫ','Маленький спутник.<br>Большая часть образа.','Выбирай курьера и сочетай поддерживаемые эффекты и призматические цвета.','<figure class="courier-feature"><img src="assets/courier-10478.png" alt="Lava Baby Roshan из Dota 2"><figcaption>Lava Baby Roshan <span>Курьер / Dota 2</span></figcaption></figure>'],world:['ПОГОДА / ЛАНДШАФТЫ / ИНТЕРФЕЙС','Атмосфера<br>по настроению.','Настраивай окружение, интерфейс и звуки. Все выбранные изменения собираются в одном профиле.','<img class="wide" src="assets/interface.png" alt="Коллекция интерфейсов Dota 2 в M3 Changer">']};
const tabs=[...document.querySelectorAll('[data-category]')];function selectTab(t){tabs.forEach(b=>{b.setAttribute('aria-selected',String(b===t));b.tabIndex=b===t?0:-1});const [tag,title,description,art]=data[t.dataset.category];$('#categoryTag').textContent=tag;$('#categoryTitle').innerHTML=title;$('#categoryText').textContent=description;$('#collectionArt').innerHTML=art;$('#categoryPanel').setAttribute('aria-labelledby',t.id)}tabs.forEach((t,i)=>{t.onclick=()=>selectTab(t);t.onkeydown=e=>{let n=i;if(e.key==='ArrowRight')n=(i+1)%tabs.length;else if(e.key==='ArrowLeft')n=(i+tabs.length-1)%tabs.length;else if(e.key==='Home')n=0;else if(e.key==='End')n=tabs.length-1;else return;e.preventDefault();selectTab(tabs[n]);tabs[n].focus()}});

$('.app-zoom').onclick=()=>$('#lightbox').showModal();document.querySelectorAll('dialog').forEach(d=>{d.querySelectorAll('.dialog-close,.dialog-close-action').forEach(b=>b.onclick=()=>d.close());d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}})});

let heroInView=true;new IntersectionObserver(es=>heroInView=es[0].isIntersecting).observe($('.hero-stage'));
let mouseFrame=0;$('.hero-stage').addEventListener('pointermove',e=>{if(!motion||!heroInView||e.pointerType==='touch'||mouseFrame)return;mouseFrame=requestAnimationFrame(()=>{const r=$('.hero-stage').getBoundingClientRect();$('.hero-orbit').style.transform=`rotate(-28deg) translate(${(e.clientX-r.left-r.width/2)*.035}px,${(e.clientY-r.top-r.height/2)*.035}px)`;mouseFrame=0})});

// Load footage near the viewport; pause offscreen and honour motion preferences.
const comparison=$('.comparison'),range=$('#comparisonRange');
const videos=[$('#vanillaVideo'),$('#moddedVideo')],playButton=$('#comparisonPlay');
let comparisonVisible=false,ready=false,userPaused=false,userInteracted=false,demoFrame=0,demoDone=false,playbackEpoch=0;
function position(value){range.value=String(value);comparison.style.setProperty('--position',value+'%');range.setAttribute('aria-valuetext',`Новое окружение — ${Math.round(value)} процентов`);$('.compare-label.left').style.opacity=value<18?'0':'1';$('.compare-label.right').style.opacity=value>82?'0':'1'}
function updatePlayback(){const epoch=++playbackEpoch;const play=ready&&comparisonVisible&&!document.hidden&&motion&&!userPaused;videos.forEach(v=>{if(play)v.play().catch(error=>{if(epoch!==playbackEpoch||error.name==='AbortError')return;userPaused=true;videos.forEach(x=>x.pause());playButton.textContent='Воспроизвести';playButton.setAttribute('aria-pressed','false')});else v.pause()});playButton.textContent=play?'Пауза':'Воспроизвести';playButton.setAttribute('aria-pressed',String(play));if(!play)cancelAnimationFrame(demoFrame)}
function demo(){if(demoDone||userInteracted||!motion||!comparisonVisible||document.hidden)return;demoDone=true;const start=performance.now();function frame(now){if(userInteracted||!motion||!comparisonVisible||document.hidden)return;const t=Math.min(1,(now-start)/2200);position(50+18*Math.sin(t*2*Math.PI)*Math.sin(t*Math.PI));if(t<1)demoFrame=requestAnimationFrame(frame);else position(50)}demoFrame=requestAnimationFrame(frame)}
function interact(){userInteracted=true;cancelAnimationFrame(demoFrame)}
range.addEventListener('input',()=>{interact();position(Number(range.value))});range.addEventListener('keydown',interact);
let pointer=null;
range.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;interact();pointer=e.pointerId;range.setPointerCapture(pointer);comparison.classList.add('dragging');if(e.pointerType!=='touch')move(e)});
function move(e){if(e.pointerId!==pointer)return;const rect=comparison.getBoundingClientRect();position(Math.max(0,Math.min(100,(e.clientX-rect.left)/rect.width*100)))}
range.addEventListener('pointermove',move);function release(){pointer=null;comparison.classList.remove('dragging')}range.addEventListener('pointerup',release);range.addEventListener('pointercancel',release);range.addEventListener('lostpointercapture',release);
function loaded(){if(!ready&&videos.every(v=>v.readyState>=2)){ready=true;comparison.dataset.state='ready';playButton.disabled=false;updatePlayback();demo()}}
videos.forEach(v=>{v.addEventListener('loadeddata',loaded);v.addEventListener('canplay',loaded);v.addEventListener('error',()=>{comparison.dataset.state='error';comparison.querySelector('.compare-status').textContent='Не удалось загрузить видео. Проверь подключение и обнови страницу.';ready=false;playButton.disabled=true;updatePlayback()})});
new IntersectionObserver(entries=>{comparisonVisible=entries[0].isIntersecting;if(comparisonVisible)videos.forEach(v=>{if(!v.hasAttribute('src')){v.src=v.dataset.src;v.load()}});updatePlayback();if(ready&&comparisonVisible)demo()},{rootMargin:'120px',threshold:0}).observe(comparison);
// Correct drift only when both videos are playing; avoid per-frame JS work.
videos[0].addEventListener('timeupdate',()=>{const [a,b]=videos;if(a.paused||b.paused||b.seeking||b.readyState<2)return;if(Math.abs(a.currentTime-b.currentTime)>.15)b.currentTime=a.currentTime});
playButton.onclick=()=>{interact();userPaused=!userPaused;if(!userPaused&&!motion)setMotion(true);updatePlayback()};
new MutationObserver(updatePlayback).observe(document.body,{attributes:true,attributeFilter:['class']});document.addEventListener('visibilitychange',updatePlayback);
