(() => {
 const $=selector=>document.querySelector(selector);
 const dialog=$('#authDialog'),form=$('#authForm'),message=$('#authMessage');
 let user=null,csrf='',settings={providers:{},download:{}},mode='register',ready=false,busy=false,previousHash='';
 const messages={google_unavailable:'Вход через Google пока недоступен. Войди по email.',apple_unavailable:'Вход через Apple пока недоступен. Войди по email.',account_exists:'Аккаунт с этим email уже существует. Войди тем способом, которым регистрировался.',oauth_failed:'Вход не завершён. Попробуй ещё раз или войди по email.'};
 function announce(element,text,error=false){element.textContent=text;element.classList.toggle('is-error',error);}
 async function api(path,method='GET',data){const response=await fetch(path,{method,credentials:'same-origin',headers:{...(data?{'Content-Type':'application/json'}:{}),...(method!=='GET'?{'X-CSRF-Token':csrf}:{})},...(data?{body:JSON.stringify(data)}:{})});let result;try{result=await response.json();}catch{throw Error('Для входа нужен работающий сервер сайта.');}if(!response.ok)throw Error(result.error||'Не удалось выполнить действие.');if(result.csrf)csrf=result.csrf;return result;}
 function setMode(value){mode=value;const registering=mode==='register';$('#authTitle').textContent=registering?'Твоя коллекция начинается здесь.':'С возвращением.';$('#authSubtitle').textContent=registering?'Создай аккаунт M3 или продолжи через удобный сервис.':'Войди, чтобы открыть личный кабинет.';$('#authSubmit').textContent=registering?'Создать аккаунт':'Войти';document.querySelectorAll('[data-auth-mode]').forEach(button=>{const selected=button.dataset.authMode===mode;button.setAttribute('aria-selected',String(selected));button.tabIndex=selected?0:-1;});document.querySelectorAll('[data-register-only]').forEach(element=>{element.hidden=!registering;element.querySelectorAll('input').forEach(input=>{input.disabled=!registering;input.required=registering&&input.name!=='promo';});});$('#authPassword').autocomplete=registering?'new-password':'current-password';$('#authPassword').minLength=registering?10:1;$('#authPassword').placeholder=registering?'Не менее 10 символов':'Твой пароль';announce(message,'');}
 function paintAccount(){document.dispatchEvent(new CustomEvent('m3-session',{detail:{user,csrf,settings}}));const signedIn=!!user;$('#accountButton').textContent=signedIn?'Личный кабинет':'Войти';if(!user)return;$('#accountName').textContent=user.name;$('#accountEmail').textContent=user.email;$('#accountAvatar').textContent=Array.from(user.name)[0].toUpperCase();$('#profileName').value=user.name;$('#profileEmail').value=user.email;$('#profilePromo').textContent=user.promo_code||'Не указан';$('#profileCreated').textContent=new Date(user.created_at*1000).toLocaleDateString('ru-RU');$('#profileProviders').textContent=[...(user.hasPassword?['Email и пароль']:[]),...user.providers.map(p=>p==='google'?'Google':'Apple')].join(' · ');$('#downloadVersion').textContent='M3 Changer '+settings.download.version;$('#accountDownload').disabled=!settings.download.available;$('#downloadAvailability').textContent=settings.download.available?'Windows 10 / 11 · нужен установленный Dota 2':'Новая сборка пока недоступна. Загляни позже.';}
 function showLanding(){document.querySelector('main').hidden=false;$('#accountView').hidden=true;}
 function route(){if(!ready)return;const wasAccount=!$('#accountView').hidden;const fragment=location.hash.slice(1);if(fragment.startsWith('account/')){if(!user){location.hash='auth?mode=login';return;}if(dialog.open)dialog.close();document.querySelector('main').hidden=true;$('#accountView').hidden=false;const tab=fragment.split('/')[1];const selected=['profile','access','download'].includes(tab)?tab:'profile';document.querySelectorAll('[data-account-tab]').forEach(button=>{const active=button.dataset.accountTab===selected;button.setAttribute('aria-selected',String(active));button.tabIndex=active?0:-1;});document.querySelectorAll('[data-account-panel]').forEach(panel=>panel.hidden=panel.dataset.accountPanel!==selected);paintAccount();return;}showLanding();if(wasAccount&&!fragment.startsWith('auth'))requestAnimationFrame(()=>document.getElementById(fragment)?.scrollIntoView({behavior:motion?'smooth':'instant'}));if(fragment.startsWith('auth')){if(user){location.hash='account/profile';return;}const params=new URLSearchParams(fragment.split('?')[1]);setMode(params.get('mode')==='login'?'login':'register');if(!dialog.open)dialog.showModal();if(params.has('error'))announce(message,messages[params.get('error')]||messages.oauth_failed,true);if(!csrf)announce(message,'Сервер входа недоступен. Обнови страницу после запуска сайта.',true);}else if(dialog.open)dialog.close();}
 document.querySelectorAll('[data-open-auth]').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();previousHash=location.hash;if(user)location.hash='account/profile';else location.hash='auth?mode='+button.dataset.openAuth;if(location.hash.startsWith('#auth'))route();}));
 $('#accountButton').addEventListener('click',()=>{previousHash=location.hash;location.hash=user?'account/profile':'auth?mode=login';route();});
 document.querySelectorAll('[data-auth-mode]').forEach((button,index,buttons)=>{button.addEventListener('click',()=>setMode(button.dataset.authMode));button.addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const next=event.key==='Home'?0:event.key==='End'?buttons.length-1:(index+1)%buttons.length;buttons[next].focus();setMode(buttons[next].dataset.authMode);});});
 dialog.addEventListener('close',()=>{form.reset();$('#authPassword').type='password';$('#passwordReveal').setAttribute('aria-pressed','false');$('#passwordReveal').textContent='Показать';if(location.hash.startsWith('#auth')){history.replaceState(null,'',previousHash||location.pathname);showLanding();}});
 $('#passwordReveal').addEventListener('click',()=>{const shown=$('#authPassword').type==='text';$('#authPassword').type=shown?'password':'text';$('#passwordReveal').textContent=shown?'Показать':'Скрыть';$('#passwordReveal').setAttribute('aria-pressed',String(!shown));});
 form.addEventListener('submit',async event=>{event.preventDefault();if(busy)return;if(!csrf){announce(message,'Сервер входа недоступен. Обнови страницу после запуска сайта.',true);return;}if(mode==='register'&&$('#authPassword').value!==$('#authConfirm').value){announce(message,'Пароли не совпадают.',true);$('#authConfirm').focus();return;}busy=true;$('#authSubmit').disabled=true;$('#authSubmit').textContent=mode==='register'?'Создаём аккаунт…':'Входим…';form.setAttribute('aria-busy','true');announce(message,'');try{const values=Object.fromEntries(new FormData(form));const result=await api(mode==='register'?'/api/register':'/api/login','POST',values);user=result.user;paintAccount();location.hash='account/profile';route();}catch(error){announce(message,error.message==='Failed to fetch'?'Нет соединения с сервером. Попробуй ещё раз.':error.message,true);}finally{busy=false;$('#authSubmit').disabled=false;$('#authSubmit').textContent=mode==='register'?'Создать аккаунт':'Войти';form.setAttribute('aria-busy','false');}});
 document.querySelectorAll('[data-oauth]').forEach(button=>button.addEventListener('click',()=>{const provider=button.dataset.oauth;if(!settings.providers[provider]){announce(message,messages[provider+'_unavailable'],true);return;}const promo=mode==='register'?$('#authPromo').value.trim():'';if(promo&&!$('#authPromo').checkValidity()){$('#authPromo').reportValidity();return;}location.assign('/auth/'+provider+(promo?'?promo='+encodeURIComponent(promo):''));}));
 document.querySelectorAll('[data-account-tab]').forEach((button,index,buttons)=>{button.addEventListener('click',()=>location.hash='account/'+button.dataset.accountTab);button.addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const next=event.key==='Home'?0:event.key==='End'?buttons.length-1:(index+(event.key==='ArrowRight'?1:buttons.length-1))%buttons.length;buttons[next].focus();location.hash='account/'+buttons[next].dataset.accountTab;});});
 $('#profileForm').addEventListener('submit',async event=>{event.preventDefault();const button=$('#profileSave');button.disabled=true;announce($('#profileMessage'),'');try{user=(await api('/api/profile','PATCH',{name:$('#profileName').value})).user;paintAccount();announce($('#profileMessage'),'Изменения сохранены.');}catch(error){announce($('#profileMessage'),error.message,true);}finally{button.disabled=false;}});
 $('#logoutButton').addEventListener('click',async()=>{const button=$('#logoutButton');button.disabled=true;try{await api('/api/logout','POST',{});user=null;paintAccount();location.hash='top';route();}catch(error){announce($('#accountMessage'),error.message,true);}finally{button.disabled=false;}});
 $('#accountDownload').addEventListener('click',()=>{if(user&&settings.download.available)location.assign('/api/download');});
 document.addEventListener('m3-email-verified',event=>{if(event.detail){user=event.detail;paintAccount();}});
 addEventListener('hashchange',route);
 (async()=>{try{const result=await api('/api/session');user=result.user;settings=result;}catch{announce($('#accountMessage'),'Не удалось соединиться с сервером. Обнови страницу.',true);}finally{ready=true;paintAccount();route();}})();
})();
