// Public contact details only. Add your links here when they are ready.
const M3_CONTACTS={owner:'',requisites:'',email:'',vk:'',youtube:'',telegram:'',discord:'',supportOnline:false};

(() => {
 const dialog=document.getElementById('infoDialog'),content=document.getElementById('infoContent');let previousHash='';
 const icons={
  vk:'<path d="M3 5h3c.2 5 2 8 3.5 8V5h3v4.6c1.5-.2 3.2-2.6 4-4.6h3c-.7 2.4-2.5 4.8-4.3 6.2 1.8 1.3 3.8 3.5 4.8 6.8h-3.3c-.8-2.1-2.4-4.3-4.2-4.6V18h-1.3C6.2 18 3.4 13.7 3 5Z"/>',
  youtube:'<path d="M21.5 7.2a3 3 0 0 0-2.1-2.1C17.6 4.6 12 4.6 12 4.6s-5.6 0-7.4.5a3 3 0 0 0-2.1 2.1A31 31 0 0 0 2 12a31 31 0 0 0 .5 4.8 3 3 0 0 0 2.1 2.1c1.8.5 7.4.5 7.4.5s5.6 0 7.4-.5a3 3 0 0 0 2.1-2.1A31 31 0 0 0 22 12a31 31 0 0 0-.5-4.8ZM10 15.3V8.7l5.7 3.3-5.7 3.3Z"/>',
  telegram:'<path d="m21.3 3.1-3.5 17c-.3 1.2-1 1.5-2 .9l-5.3-3.9-2.5 2.4c-.3.3-.5.5-1 .5l.4-5.5L17.6 5.3c.5-.4-.1-.6-.7-.2L4.3 13 1.2 12c-1-.3-1.1-1 .2-1.5L20 3.3c.9-.3 1.5.2 1.3-.2Z"/>',
  discord:'<path d="M19.5 5.3a17 17 0 0 0-4.3-1.4l-.5 1.1a16 16 0 0 0-5.4 0l-.5-1.1a17 17 0 0 0-4.3 1.4C1.8 9.3 1.1 13.2 1.5 17a18 18 0 0 0 5.3 2.7l1.1-1.8-1.7-.8.4-.3a15 15 0 0 0 10.8 0l.4.3-1.7.8 1.1 1.8a18 18 0 0 0 5.3-2.7c.5-4.5-.7-8.4-3-11.7ZM8.5 14.4c-1 0-1.8-.9-1.8-2s.8-2 1.8-2 1.8.9 1.8 2-.8 2-1.8 2Zm7 0c-1 0-1.8-.9-1.8-2s.8-2 1.8-2 1.8.9 1.8 2-.8 2-1.8 2Z"/>'
 };
 const labels={vk:'ВКонтакте',youtube:'YouTube',telegram:'Telegram',discord:'Discord'};
 function contactLink(type){const value=M3_CONTACTS[type];if(!value)return null;try{const url=new URL(value);const hosts={vk:['vk.com','vk.ru'],youtube:['youtube.com','www.youtube.com','youtu.be'],telegram:['t.me'],discord:['discord.gg','discord.com']};return url.protocol==='https:'&&hosts[type].includes(url.hostname)?url.href:null;}catch{return null;}}
 function socialList(root){for(const type of Object.keys(labels)){const url=contactLink(type),link=document.createElement('a');link.className='social-icon';link.setAttribute('aria-label',labels[type]);link.title=labels[type]+(url?'':' — ссылка появится позже');link.innerHTML=`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[type]}</svg>`;if(url){link.href=url;link.target='_blank';link.rel='noopener noreferrer';}else{link.href='#legal/contacts';link.addEventListener('click',e=>{e.preventDefault();open('contacts');});}root.append(link);}}
 document.querySelectorAll('[data-social-links]').forEach(socialList);
 const documents={
  contacts:{title:'Контакты',body:`<p class="info-lead">Есть вопрос об аккаунте, оплате или M3? Здесь появятся каналы связи с командой.</p><div id="contactDetails"></div><div class="contact-socials" data-contact-socials></div><p class="info-note">Контактные адреса и ссылки будут добавлены владельцем проекта. Сейчас сообщение через сайт не отправляется.</p>`},
  license:{title:'Лицензионное соглашение',body:`<p class="info-lead">Условия использования M3 Changer и доступа к программе.</p><h3>1. Программа и доступ</h3><p>M3 Changer — самостоятельная программа для локального изменения визуального оформления Dota 2. Доступ предоставляется на срок выбранной и оплаченной подписки. Покупка не передаёт права собственности на программу или игровые предметы.</p><h3>2. Аккаунт и активация</h3><p>Пользователь указывает свой email, подтверждает его и хранит пароль в тайне. Ключ выдаётся после подтверждения оплаты и привязывается к указанному ID установки компьютера и профилю Windows. Проверь ID перед покупкой. Для продления на том же компьютере используй новый ключ из кабинета.</p><h3>3. Использование</h3><p>Разрешается устанавливать и использовать программу в пределах оплаченного доступа. Нельзя распространять чужие ключи, продавать копии программы без разрешения владельца или обходить проверку лицензии. Пользователь соблюдает применимые правила игры и платформы.</p><h3>4. Обновления и совместимость</h3><p>Для работы необходима совместимая версия Windows и установленная Dota 2. Обновления игры могут влиять на доступность отдельных функций и оформление. Функции сервиса не изменяют право собственности на предметы в Steam и не оформляют подписку Valve.</p><h3>5. Оплата и обращения</h3><p>Срок и цена показываются перед оплатой. Промокод автора сохраняет источник регистрации; скидка применяется только при явно указанных условиях акции. Автоматического продления со списанием денег сейчас нет. По вопросам ошибочного ID, недоступного доступа или возврата обратись к владельцу через раздел «Контакты». Применяются обязательные права пользователя по действующему законодательству.</p><h3>6. Права и изменения</h3><p>Dota 2, Steam и игровые материалы принадлежат их правообладателям. M3 не является официальным продуктом Valve. Новая редакция условий публикуется на сайте; условия уже оплаченного заказа определяются его подтверждёнными параметрами.</p>`},
  payments:{title:'Безопасность платежей',body:`<p class="info-lead">Оплата через СБП и выдача ключа после подтверждения платежа.</p><h3>Как проходит оплата</h3><p>В кабинете выбери тариф и укажи ID установки. Сайт создаёт заказ с зафиксированной суммой в рублях и перенаправляет на страницу платёжного провайдера ЮKassa. Подтверждение СБП выполняется в банковском приложении покупателя.</p><h3>Какие данные получает M3</h3><p>Пароли банка, банковские коды подтверждения и реквизиты карты не вводятся на сайте M3. Сайт хранит номер заказа, выбранный тариф, сумму, статус платежа и ID установки. Если для заказа нужен чек, email передаётся платёжному провайдеру.</p><h3>Проверка и выдача</h3><p>Сервер проверяет статус, сумму и валюту через API ЮKassa. Возврат на сайт или стороннее уведомление сами по себе не подтверждают оплату. После успешной проверки ключ появляется в личном кабинете. Повторное уведомление не создаёт дополнительный ключ.</p><h3>Если платёж не завершён</h3><p>Открой историю заказов: оттуда можно продолжить оплату или проверить её статус. Не повторяй покупку, если деньги уже списаны, а ключ ещё не появился. Сохрани номер заказа и обратись через раздел «Контакты». Не сообщай пароль банка, коды подтверждения или пароль аккаунта.</p><h3>Тестовый режим</h3><p>Пока платёжный сервис не подключён, покупка отключена. При тестовом подключении в кабинете явно отображается тестовый режим. Реальные платежи включаются владельцем после настройки магазина.</p>`},
  privacy:{title:'Политика конфиденциальности',body:`<p class="info-lead">Какие данные нужны для аккаунта, подписки и работы сайта M3.</p><h3>1. Какие данные обрабатываются</h3><p>Имя, email, хеш пароля, отметка подтверждения email, дата регистрации и необязательный промокод автора. При социальном входе — идентификатор и подтверждённые сведения от Google или Apple. При покупке — ID установки, тариф, сумма, статус заказа, срок доступа и выданный ключ.</p><h3>2. Для чего они нужны</h3><p>Для регистрации, входа, подтверждения почты, сохранения профиля, учёта платежей, выдачи лицензии и ответов на обращения. Технические записи сессий и попыток входа, включая IP-адрес, используются для защиты аккаунтов и ограничения злоупотреблений.</p><h3>3. Cookies и хранение</h3><p>Сайт использует необходимые cookies сессии и социального входа. Браузер хранит идентификатор незавершённой покупки для её повторения без нового заказа. Пароль хранится в виде хеша; серверные секреты не передаются в браузер. Аккаунты и заказы сохраняются на сервере, пока они нужны для обслуживания доступа, обращений и обязательного учёта.</p><h3>4. Сервисы обработки</h3><p>Для оплаты используется ЮKassa, для подтверждения почты и уведомлений — Resend. При входе через Google или Apple используются соответствующие провайдеры. Каждый получает данные, необходимые для выбранного действия. Расположение обработки зависит от подключённых сервисов и хостинга; их собственные политики также применяются.</p><h3>5. Обращения пользователя</h3><p>Имя можно изменить в профиле. Для вопросов о данных, исправления email, удаления аккаунта или отзыва согласия обратись к владельцу через «Контакты». Удаление аккаунта может прекратить доступ к кабинету; сведения, которые необходимо сохранять по закону или для разбирательства по оплате, обрабатываются в соответствующем объёме.</p><h3>6. Редакция политики</h3><p>Актуальная редакция доступна на сайте. Реквизиты оператора и рабочий адрес для обращений будут добавлены владельцем перед публичным запуском аккаунтов и оплаты.</p>`}
 };
 function render(type){const doc=documents[type];if(!doc)return false;document.getElementById('infoTitle').textContent=doc.title;content.innerHTML=doc.body;dialog.scrollTop=0;
  if(type==='contacts'){const details=document.getElementById('contactDetails');for(const [label,value] of [['Владелец',M3_CONTACTS.owner],['Реквизиты',M3_CONTACTS.requisites],['Email',M3_CONTACTS.email]])if(value){const p=document.createElement('p');const strong=document.createElement('strong');strong.textContent=label+': ';p.append(strong,document.createTextNode(value));details.append(p);}socialList(content.querySelector('[data-contact-socials]'));}
  return true;
 }
 function open(type){if(!render(type))return;if(!location.hash.startsWith('#legal/'))previousHash=location.hash;history.replaceState(null,'','#legal/'+type);if(!dialog.open)dialog.showModal();}
 document.querySelectorAll('[data-document]').forEach(link=>link.addEventListener('click',e=>{e.preventDefault();open(link.dataset.document);}));
 dialog.addEventListener('close',()=>{if(location.hash.startsWith('#legal/'))history.replaceState(null,'',previousHash||location.pathname);});
 function deepLink(){if(location.hash.startsWith('#legal/'))open(location.hash.slice(7));}addEventListener('hashchange',deepLink);deepLink();
 const support=document.getElementById('supportPanel'),toggle=document.getElementById('supportToggle');
 const online=M3_CONTACTS.supportOnline&&!!(contactLink('telegram')||M3_CONTACTS.email);document.getElementById('supportStatus').textContent=online?'Мы онлайн':'Контакты скоро';toggle.classList.toggle('is-online',online);
 toggle.addEventListener('click',()=>{support.hidden=!support.hidden;toggle.setAttribute('aria-expanded',String(!support.hidden));});
 document.getElementById('supportClose').addEventListener('click',()=>{support.hidden=true;toggle.setAttribute('aria-expanded','false');toggle.focus();});
 document.getElementById('supportContacts').addEventListener('click',()=>{support.hidden=true;toggle.setAttribute('aria-expanded','false');open('contacts');});
 const direct=document.getElementById('supportDirect'),telegram=contactLink('telegram');if(telegram){direct.href=telegram;direct.target='_blank';direct.rel='noopener noreferrer';direct.textContent='Написать в Telegram';direct.hidden=false;}else if(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(M3_CONTACTS.email)){direct.href='mailto:'+M3_CONTACTS.email;direct.textContent='Написать на почту';direct.hidden=false;}
})();
